name: 'AI Code Review'
description: 'Perform code review using various AI models from OpenAI, Anthropic, Google, X or Deepseek'
branding:
  icon: 'book-open'
  color: 'yellow'

inputs:
  token:
    description: 'GitHub token'
    required: true
  ai_provider:
    description: 'AI provider to use (openai, anthropic, google or deepseek)'
    required: true
    default: 'openai'
  openai_api_key:
    description: 'OpenAI API key (required if using OpenAI provider)'
    required: false
  openai_model:
    description: 'OpenAI model name (e.g., gpt-4.1 or o3)'
    required: false
    default: 'gpt-4.1'
  anthropic_api_key:
    description: 'Anthropic API key (required if using Anthropic provider)'
    required: false
  anthropic_model:
    description: 'Anthropic model name (e.g., claude-sonnet-4-20250514 or claude-opus-4-20250514)'
    required: false
    default: 'claude-sonnet-4-20250514'
  google_api_key:
    description: 'Google AI API key (required if using Google provider)'
    required: false
  google_model:
    description: 'Google model name (e.g., gemini-2.5-flash or gemini-2.5-pro)'
    required: false
    default: 'gemini-2.5-flash'
  deepseek_api_key:
    description: 'Deepseek API key (required if using Deepseek provider)'
    required: false
  deepseek_model:
    description: 'Deepseek model name (e.g., deepseek-chat)'
    required: false
    default: 'deepseek-chat'
  x_api_key:
    description: 'X API key (required if using X provider)'
    required: false
  x_model:
    description: 'X model name (e.g., grok-3 or grok-4)'
    required: false
    default: 'grok-3'
  perplexity_api_key:
    description: 'Perplexity API key (required if using Perplexity provider)'
    required: false
  perplexity_model:
    description: 'Perplexity model name (e.g., sonar, sonar-pro, r1-1776, sonar-reasoning-pro)'
    required: false
    default: 'sonar-reasoning-pro'
  owner:
    description: 'Repository owner'
    required: true
  repo:
    description: 'Repository name'
    required: true
  pr_number:
    description: 'Pull request number'
    required: true
  include_extensions:
    description: 'File extensions to include in the review (comma-separated, e.g., ".py,.js,.html")'
    required: false
  exclude_extensions:
    description: 'File extensions to exclude from the review (comma-separated)'
    required: false
  include_paths:
    description: 'Paths to include in the review (comma-separated)'
    required: false
  exclude_paths:
    description: 'Paths to exclude from review (comma-separated, e.g., "test/,docs/")'
    required: false
  fail_action_if_review_failed:
    description: 'If set to true, the action fails when the review process fails'
    required: false
    default: 'false'
  review_rules_file:
    description: 'Path to a file containing custom review rules to be added to the AI system prompt.'
    required: false

runs:
  using: 'node20'
  pre: 'setup.js'
  main: 'src/index.js'
