name: 'AI Code Review'
description: 'Perform code review using various AI models (OpenAI, Google, Anthropic, Deepseek)'

inputs:
  token:
    description: 'GitHub token'
    required: true
  ai_provider:
    description: 'AI provider to use (openai, google, anthropic, or deepseek)'
    required: true
    default: 'openai'
  openai_api_key:
    description: 'OpenAI API key (required if using OpenAI provider)'
    required: false
  openai_model:
    description: 'OpenAI model name (e.g., gpt-4o, o3-mini)'
    required: false
    default: 'gpt-4o'
  google_api_key:
    description: 'Google AI API key (required if using Google provider)'
    required: false
  google_model:
    description: 'Google model name (e.g., gemini-2.0-flash-thinking-exp-01-21)'
    required: false
    default: 'gemini-2.0-flash-thinking-exp-01-21'
  anthropic_api_key:
    description: 'Anthropic API key (required if using Anthropic provider)'
    required: false
  anthropic_model:
    description: 'Anthropic model name (e.g., claude-3-5-sonnet-20241022)'
    required: false
    default: 'claude-3-5-sonnet-20241022'
  deepseek_api_key:
    description: 'Deepseek API key (required if using Deepseek provider)'
    required: false
  deepseek_model:
    description: 'Deepseek model name (e.g., deepseek-reasoner)'
    required: false
    default: 'deepseek-reasoner'
  owner:
    description: 'Repository owner'
    required: true
  repo:
    description: 'Repository name'
    required: true
  pr_number:
    description: 'Pull request number'
    required: true
  include_extensions:
    description: 'File extensions to include in the review (comma-separated, e.g., ".py,.js,.html")'
    required: false
  exclude_extensions:
    description: 'File extensions to exclude from the review (comma-separated)'
    required: false
  include_paths:
    description: 'Paths to include in the review (comma-separated)'
    required: false
  exclude_paths:
    description: 'Paths to exclude from review (comma-separated, e.g., "test/,docs/")'
    required: false
  fail_action_if_review_failed:
    description: 'If set to true, the action fails when the review process fails'
    required: false
    default: 'false'

runs:
  using: 'node20'
  pre: 'setup.js'
  main: 'index.js'